title: 'QGC-Gov: User Manual'
fontsize: 12pt
mainfont: DejaVu Sans

# highlight urls
colorlinks: true
linkcolor: blue  #internal link
urlcolor: red #external link
#toccolor: gray

author: Version [not set]
header-includes: |
    \usepackage{tcolorbox}
    \newtcolorbox{myquote}{colback=green!5!white, colframe=green!75!black}
    \renewenvironment{quote}{\begin{myquote}}{\end{myquote}}
    \usepackage{fancyhdr}
    \pagestyle{fancy}
    \fancyhead[L]{\includegraphics[width=5mm]{docs/images/image170.png}}
    \fancyhead[R]{QGC-Gov: User Manual}
    \fancyfoot[C]{\thepage}
    \fancyfoot[R]{}
