title: 'QGC-Gov: User Manual'
fontsize: 12pt
mainfont: DejaVu Sans
geometry: margin=1in

# highlight urls
colorlinks: true
linkcolor: blue  #internal link
urlcolor: red #external link
#toccolor: gray

author: Version [not set]
#options for setlist bullet, diamond, etc are:
# - http://www-h.eng.cam.ac.uk/help/tpl/textprocessing/latex_advanced/node14.html
# - https://artofproblemsolving.com/wiki/index.php/LaTeX:Symbols
header-includes: |

    \usepackage{tcolorbox}
    \newtcolorbox{myquote}{colback=green!5!white, colframe=green!75!black}
    \renewenvironment{quote}{\begin{myquote}}{\end{myquote}}
    \usepackage{fancyhdr}
    \pagestyle{fancy}
    \fancyhead[L]{\includegraphics[width=5mm]{docs/images/image170.png}}
    \fancyhead[R]{QGC-Gov: User Manual}
    \fancyfoot[C]{\thepage}
    \fancyfoot[R]{}

    \usepackage{enumitem}
    \usepackage{amsfonts}
    \setlist[itemize,1]{label=$\bullet$}
    \setlist[itemize,2]{label=$\circ$}
    \setlist[itemize,3]{label=$\cdot$}
    \setlist[itemize,5]{label=$\textopenbullet$}

    \let\originalParaGraph\paragraph
    \renewcommand{\paragraph}[1]{\originalParaGraph{#1} \hfill}

    \let\originalSubParaGraph\subparagraph
    \renewcommand{\subparagraph}[1]{\originalSubParaGraph{#1} \hfill}

