# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
    paths:
        - 'docs/**'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
        - 'docs/**'



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  convert_via_pandoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: 8BitJonny/gh-get-current-pr@1.4.0
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
      - run: echo "Your PR is ${prNumber}"
        if: success() && steps.PR.outputs.number
        env:
          prNumber: ${{ steps.PR.outputs.number }}
     
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
     
      - name: create output directory
        run: |
          mkdir output  # create output dir
      
      - uses: docker://jenosam/pandoc-with-fonts
        with:
          #args: >-  # allows you to break string into multiple lines
          #  --standalone
          #  --resource-path=.:docs:docs/images
          #  --output=output/QGC-Gov-User-Manual_PR{{steps.PR.outputs.number}}.pdf
          #  docs/README.md
          #args: --standalone --resource-path=.:docs:docs/images --output=output/QGC-Gov-User-Manual_PR${{steps.PR.outputs.number}}.pdf docs/README.md #Works
          # args: --standalone --resource-path=.:docs:docs/images --output=output/QGC-Gov-User-Manual${{env.prNumber}}.pdf docs/README.md  # env is empty
          args: --defaults=docs/defaults.yaml --output=output/QGC-Gov-User-Manual_${{steps.PR.outputs.number}}_${{ steps.tagName.outputs.tag }}.pdf  --variable=author:${{ steps.tagName.outputs.tag }}
          
          
          
          
      - uses: actions/upload-artifact@master
        with:
          name: qgc-gov-user-manual
          path: output
